### PR TITLE
Define hash methods

### PR DESCRIPTION
**Pull request by omus**
Addresses this problem:
```julia
julia> using Intervals, TimeZones

julia> n = now(tz"America/Winnipeg")
2018-07-25T15:06:54.901-05:00

julia> a = Interval(n, n)
Interval{TimeZones.ZonedDateTime}(2018-07-25T15:06:54.901-05:00, 2018-07-25T15:06:54.901-05:00, Inclusivity(true, true))

julia> b = deepcopy(a)
Interval{TimeZones.ZonedDateTime}(2018-07-25T15:06:54.901-05:00, 2018-07-25T15:06:54.901-05:00, Inclusivity(true, true))

julia> hash(a) == hash(b)
false

julia> isequal(a, b)
true
```

### CODE REVIEW

**Comment by rofinn** [comment]
Wouldn't it be easier to just use AutoHashEquals.jl?

**Comment by omus** [comment]
> Wouldn't it be easier to just use AutoHashEquals.jl?

I usually use AutoHashEquals but in packages with very few dependencies I try to avoid it if it's simple enough.

**Comment by omus** [comment]
I should have ran the full test suite locally. Stand by.

**Comment by omus** [comment]
Ok, so there was a slight wrinkle with `AnchoredInterval` which has parameterized information which we need to include in the hash. Since AutoHashEquals doesn't deal with the parametric values I'm just doing our own thing.

**Comment by omus** [comment]
The last commit changes how hashing works so that it is possible that `Interval` and `AnchoredInterval` types can hash to the same value. This reflects how Julia hashes number. e.g. `hash(1//2) == hash(0.5)`

**Pull request merged**
